baseURL: https://ikitsu.moe/
languageCode: en-us
title: "Magic Shop of Raspberry"
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About
          url: about/
          weight: 5
        - name: Posts
          url: posts/
          weight: 6
        - name: Archives
          url: archives/
          weight: 7
        - name: Friends
          url: friends/
          weight: 8
        - name: Tags
          url: tags/
          weight: 9
        - name: Categories
          url: categories/
          weight: 10
        - name: Search
          url: search/
          weight: 11

    params:
      profileMode:
        enabled: true
        title: "Magic Shop of Raspberry"
        subtitle: "Ikitsu's blog."
        imageUrl: "/images/avatar.png"
        imageTitle: "avatar"
        imageWidth: 140
        imageHeight: 140

params:
  env: production
  keywords: [Blog, OpenSource, Coding, Programming]
  author: "Ikitsu"
  defaultTheme: auto
  disableThemeToggle: false

  ShowToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  displayFullLangName: true
  mathjax: true

  homeInfoParams:
    Title: "Magic Shop of Raspberry"
    Content: "Ikitsu's blog."


  profileMode:
    enabled: true
    title: "Magic Shop of Raspberry"
    subtitle: "Ikitsu's blog."
    imageUrl: "/images/avatar.png"
    imageTitle: "avatar.png"
    imageWidth: 140
    imageHeight: 140
    mainSections:
      - posts

  socialIcons:
    - name: github
      url: "https://github.com/ikitsuchi"
    - name: twitter
      url: "https://twitter.com/ikitsuchi"
    - name: Telegram
      url: "https://t.me/ikitsuchi"
    - name: email
      url: mailto:wychen325@gmail.com
    - name: RsS
      url: "index.xml"

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON