baseURL = "https://blog.weiyi.dev"
title = "Magic Shop of Raspberry"

theme = "fuji"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

## Change this two to switch between different language
languageCode = "en"           # For RSS, view https://www.rssboard.org/rss-language-codes
defaultContentLanguage = "en" # For HTML page, now support: en, zh-hans, zh-hant, ja, nl, pl, it

summaryLength = 100 # Custom summary length, add <!--more--> in post file to custom split point
paginate = 10

# googleAnalytics = "UA-000000000-0" # Set your Google Analytics UA here

[outputFormats]
[outputFormats.SearchIndex]
isPlainText = true
notAlternative = true
mediaType = "application/json"
path = "/search/"

[outputs]
home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
author = "Weiyi Chen"                # You can also set author in post front matter individually
subTitle = "A magic shop sells nothing."
defaultTheme = "auto"              # default theme when first visit (auto|dark|light)

# Source URL of the website, will appear in the footer
sourceURL = "https://github.com/dsrkafuu/hugo-theme-fuji"

# Use CloudFlare Workers to accelerate the Google Analytics
# If you are using this please comment the googleAnalytics above
# Check https://github.com/SukkaW/cloudflare-workers-async-google-analytics for more details
# googleAnalyticsTid = "UA-000000000-0"
# googleAnalyticsRoute = "https://*.*.workers.dev/"

# Google AdSense
# The AdSense code will be inserted between the head tags of your site.
# googleAdsense = "0000000000000000"

# Word counter and read time indicator in post metadata
showWordCounter = true
showReadTime = true
hideNoTagList = true

# License in the footer
showLicenseInFooter = true

# License at the end of each post
showLicense = true
showToc = true

# Copyright
copyrightStartYear = "2018"

# Open Graph & Twitter Card variables
# You can also set description and images in post front matter individually
description = "A minimal Hugo theme with nice theme color."
og = "/img/og.png"                                          # This will use the image called og.png in static/img folder

# Posts shown in homepage
mainSections = ["posts"]

# Bangumi image chart id
bgmImageChart = "439464"

# License
license = "CC BY-NC-SA 4.0"
licenseLink = "http://creativecommons.org/licenses/by-nc-sa/4.0/"

# Comments
# utterances, see: https://utteranc.es/
# utterancesRepo = "*/*"
# utterancesIssueTerm = "pathname"

# Disqus, see: https://disqus.com/admin/install/platforms/universalcode/
# disqusShortname = "*********"
# Also use DisqusJS for accessing from Mainland China, see: https://github.com/SukkaW/DisqusJS
# If you want to set multiple api key, see theme's README for more details
# disqusJSApi = "https://*********/"
# disqusJSApikey = "**********"
giscusRepo = "ikitsuchi/ikitsuchi.github.io"
giscusRepoId = "MDEwOlJlcG9zaXRvcnk0MDM1Njk0NjE="
giscusCategory = "General"
giscusCategoryId = "DIC_kwDOGA37Nc4CbwRV"
giscusMapping = "pathname"
giscusStrict = "0"
giscusReactionsEnabled = "1"
giscusEmitMetadata = "0"
giscusInputPosition = "bottom"
giscusTheme = "preferred_color_scheme"
giscusLang = "en"

# custom lazyload placeholder
# 16:9
lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
# 32:9
lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
# 8:9
lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

# Let images display in full brightness under dark mode
# disableDarkImage = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable user to embed HTML snippets in Markdown content
[markup.highlight]
codeFences = false # Disable Hugo's code highlighter

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[taxonomies]
tag = "tags"

[menu]
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
[[menu.nav]]
name = "Archives"
url = "/archives/"
weight = 2
[[menu.nav]]
name = "About"
url = "/about/"
weight = 3
[[menu.nav]]
name = "Search"
url = "/search/"
weight = 4
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5

[[menu.link]]
name = "GitHub"
url = "https://github.com/ikitsuchi"
weight = 1
[[menu.link]]
name = "Twitter"
url = "https://twitter.com/ikitsuchi"
weight = 2
[[menu.link]]
name = "bilibili"
url = "https://space.bilibili.com/24474110"
weight = 3
[[menu.link]]
name = "Telegram"
url = "https://t.me/gensou_automata"
weight = 4
[[menu.link]]
name = "Email"
url = "mailto:wychen325@gmail.com"
weight = 5

[build]
noJSConfigInAssets = true

[security]
enableInlineShortcodes = true

[imaging]
resampleFilter = "box"
quality = 75
anchor = "smart"
bgColor = "#ffffff"

[imaging.exif]
includeFields = ""
excludeFields = ".*"
disableDate = true
disableLatLong = true
