name: deploy hugo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                submodules: true
                fetch-depth: 0

          - name: Setup Hugo
            uses: peaceiris/actions-hugo@v2
            with:
                hugo-version: "latest"

          - name: Build
            run: hugo --minify --gc --cleanDestinationDir

          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
                PERSONAL_TOKEN: ${{ secrets.HUGO_DEPLOY_TOKEN }}
                PUBLISH_BRANCH: gh-pages
                PUBLISH_DIR: ./public
                commit_message: ${{ github.event.head_commit.message }}
                cname: blog.weiyi.dev